name: Generator

on:
  workflow_dispatch:
    inputs:
      account:
        description: 'Number of Accounts to be generated (default = 0)'
        required: false
        default: '0'
      key:
        description: 'Number of Keys to be generated (default = 1)'
        required: false
        default: '1'
      mail:
        description: 'Choose the mail provider to generate license'
        required: true
        type: choice
        options:
        - 1secmail
        - guerrillamail
        - developermail
        - mailticking
        - fakemail
        - inboxes
        - incognitomail
        default: fakemail
      key_type:
        description: 'Modes of operation'
        required: true
        type: choice
        options:
        - --key
        - --small-business-key
        - --vpn-codes
        default: --key
      os:
        description: 'Operating System of runner'
        required: true
        type: choice
        options:
        - macOS
        - Linux
        - Windows
        default: macOS
      branch:
        description: "Repository branch"
        required: false
        type: choice
        options:
        - main
        - test
        default: main

jobs:
  generate:
    runs-on: ${{ github.event.inputs.os == 'macOS' && 'macos-latest' || github.event.inputs.os == 'Linux' && 'ubuntu-latest' || 'windows-latest' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Generate keys
        run: |
          $ACCOUNT="${{ github.event.inputs.account }}"
          $KEY="${{ github.event.inputs.key }}"
          $MAIL="${{ github.event.inputs.mail }}"
          $KEY_TYPE="${{ github.event.inputs.key_type }}"

          if ($ACCOUNT -ne 0 -and $KEY -ne 0) {
              python main.py --auto-detect-browser --account --email-api $MAIL --skip-update-check --no-logo --disable-progress-bar --disable-logging --repeat $ACCOUNT
              python main.py --auto-detect-browser $KEY_TYPE --email-api $MAIL --skip-update-check --no-logo --disable-progress-bar --disable-logging --repeat $KEY
              echo "Account:" >> $GITHUB_STEP_SUMMARY
              Get-Content -Path ./*ACCOUNTS.txt | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
              echo "`nKey:" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
              Get-Content -Path ./*KEYS.txt | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          }
          elseif ($ACCOUNT -ne 0) {
              python main.py --auto-detect-browser --account --email-api $MAIL --skip-update-check --no-logo --disable-progress-bar --disable-logging --repeat $ACCOUNT
              echo "`nAccount:" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
              Get-Content -Path ./*ACCOUNTS.txt | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          }
          elseif ($KEY -ne 0) {
              python main.py --auto-detect-browser $KEY_TYPE --email-api $MAIL --skip-update-check --no-logo --disable-progress-bar --disable-logging --repeat $KEY
              echo "`nKey:" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
              Get-Content -Path ./*KEYS.txt | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          }
          
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: generated-files
          path: |
            *.txt
            *.log
